import fs from 'node:fs';
import {quotaLabel} from '../assets/quota.js';
import {speedCardStatus} from './speed-research.mjs';
const history=JSON.parse(fs.readFileSync(new URL('../data/brand-history.json',import.meta.url),'utf8'));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const config=JSON.parse(fs.readFileSync(new URL('../site.config.json',import.meta.url),'utf8'));
export function feedbackTemplate(b){return `品牌：${b.name} (${b.english})\n页面：${config.url}${config.basePath||''}/brands/${b.id}/\n\n需要更正的内容：\n最新资料来源（链接）：\n资料或截图日期：\n具体说明：\n\n请隐藏账号、订单号及支付信息。`;}
export const feedbackMail=b=>'mailto:ksugiono187@gmail.com?subject='+encodeURIComponent('云途集｜'+b.name+'资料反馈')+'&body='+encodeURIComponent(feedbackTemplate(b));
export function brandQuickLinks(b){return `<nav class="brand-quick-links" aria-label="${E(b.name)}资料工具"><a class="speed-shortcut" href="brands/${b.id}/#speed-records" aria-label="查看${E(b.name)}测速资料">查看测速 →<small>${E(speedCardStatus(b.id))}</small></a><a href="brands/${b.id}/#history" aria-label="查看${E(b.name)}资料变更记录">资料变更<small>从10月3日起记录</small></a><a class="brand-feedback-link" href="${E(feedbackMail(b))}" aria-label="反馈${E(b.name)}资料错误">反馈错误<small>预填品牌与页面</small></a></nav>`;}
const snapshotFields=['name','price','cycle','gb','quotedGb','quotaPeriod','unlimitedTime','quotaNote'];
export const snapshotPlans=plans=>plans.map(p=>Object.fromEntries(snapshotFields.map(k=>[k,p[k]??null]))).sort((a,b)=>(a.cycle+'\u0000'+a.name).localeCompare(b.cycle+'\u0000'+b.name));
const key=p=>p.cycle+'\u0000'+p.name;
export function referenceChanges(before,after){
 const old=new Map(before.map(p=>[key(p),p])),next=new Map(after.map(p=>[key(p),p])),changes=[];
 for(const [k,p] of old){const n=next.get(k);if(!n){changes.push({plan:p.name,cycle:p.cycle,field:'套餐记录',before:'已收录',after:'本版未收录'});continue;}for(const f of snapshotFields.filter(f=>!['name','cycle'].includes(f)))if((p[f]??null)!==(n[f]??null))changes.push({plan:p.name,cycle:p.cycle,field:f,before:p[f]??null,after:n[f]??null});}
 for(const [k,p] of next)if(!old.has(k))changes.push({plan:p.name,cycle:p.cycle,field:'套餐记录',before:'本版未收录',after:'新增收录'});
 return changes;
}
const fieldLabels={price:'参考金额（元）',gb:'明确周期的GB',quotedGb:'原资料容量（GB）',quotaPeriod:'流量周期',unlimitedTime:'不限时资料字段',quotaNote:'容量说明'};
const value=v=>v===null?'未确认':typeof v==='boolean'?(v?'是':'否'):({month:'每月',unknown:'未知', 'year-total':'全年总量',total:'一次性总量'}[v]||String(v));
export function assertHistoryMatches(brands){for(const b of brands){const r=history.records.find(r=>r.brandId===b.id),last=r?.referenceSnapshots.at(-1);if(!last||JSON.stringify(snapshotPlans(b.plans))!==JSON.stringify(snapshotPlans(last.plans)))throw Error('Brand history snapshot needs a sourced update: '+b.id);}}
export function renderBrandHistory(b){
 const r=history.records.find(r=>r.brandId===b.id);
 const versions=r.referenceSnapshots;
 const diffs=versions.slice(1).map((v,i)=>{const changes=referenceChanges(versions[i].plans,v.plans);return `<article class="history-change"><h3>${E(v.date)} · 参考资料调整</h3><p>${E(v.reason)}</p><p>依据：<a href="${E(v.source)}" target="_blank" rel="noopener noreferrer">${E(v.sourceLabel)} ↗</a>；记录性质：第三方参考，官网现价仍需另行确认。</p><div class="table-scroll"><table><caption>${E(b.name)} · 两次留存的参考资料差异，不是交易价格记录</caption><thead><tr><th>套餐 / 周期</th><th>字段</th><th>前次记录</th><th>本次记录</th></tr></thead><tbody>${changes.map(c=>`<tr><th scope="row">${E(c.plan)} / ${E(c.cycle)}</th><td>${E(fieldLabels[c.field]||c.field)}</td><td>${E(value(c.before))}</td><td>${E(value(c.after))}</td></tr>`).join('')}</tbody></table></div></article>`;}).reverse().join('');
 const first=versions[0];
 return `<section class="prose-block brand-history" id="history"><p class="eyebrow">REFERENCE HISTORY / 每次调整，留下依据</p><h2>${E(b.name)}资料变更记录</h2><p>从${E(r.startedAt)}开始留存本站资料。保存的是引用与核验过程，不是品牌经营历史；资料记录日期与原来源日期分开说明。</p>${diffs||'<p class="history-baseline-note">目前只有首次留存，暂无两次记录之间的价格变化。未保留的过去价格不补填。</p>'}<ol class="brand-history-list">${r.events.toReversed().map(e=>`<li><time datetime="${E(e.date)}">${E(e.date)}</time><h3>${E(e.title)}</h3><p>${E(e.detail)}</p><div class="inline-links">${e.sources.map(s=>`<a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">${E(s.label)} ↗</a>`).join('')}</div></li>`).join('')}</ol><details class="history-snapshot"><summary>查看首次留存的参考套餐 · ${first.plans.length}档</summary><p>本站留存${E(first.date)}；原资料日期${E(first.sourceDate)}。<a href="${E(first.source)}" target="_blank" rel="noopener noreferrer">${E(first.sourceLabel)} ↗</a>。未计优惠，未确认官网现价。</p><div class="table-scroll"><table><caption>${E(b.name)} · 初次参考资料快照</caption><thead><tr><th>套餐</th><th>参考金额</th><th>付款周期</th><th>流量口径</th></tr></thead><tbody>${first.plans.map(p=>`<tr><th scope="row">${E(p.name)}</th><td>¥${p.price}</td><td>${E(p.cycle)}</td><td>${E(quotaLabel(p))}</td></tr>`).join('')}</tbody></table></div></details></section><section class="prose-block brand-feedback" id="feedback"><p class="eyebrow">HELP US KEEP IT ACCURATE</p><h2>反馈${E(b.name)}资料错误</h2><p>价格、流量、优惠码、入口或测速引用有变化？可打开预填品牌与页面的邮件草稿，补充具体问题和新资料来源；也可复制模板，通过<a href="https://t.me/Hy_0027" target="_blank" rel="noopener noreferrer">Telegram @Hy_0027</a>发给本站。</p><div class="actions"><a class="button primary brand-feedback-link" href="${E(feedbackMail(b))}">反馈资料错误 · 打开邮件</a><button type="button" class="button secondary copy" data-copy="${E(feedbackTemplate(b))}" data-copy-kind="feedback" aria-label="复制${E(b.name)}资料反馈模板">复制反馈模板</button></div><p class="muted">仅生成草稿或复制模板，不会自动发送。请附资料日期并隐藏账号、订单号和支付信息；反馈经核对后才会更新。</p><details class="feedback-template"><summary>查看预填反馈内容</summary><pre>${E(feedbackTemplate(b))}</pre></details><a class="text-link" href="../../contact/#feedback-help">其他联系渠道与反馈说明 →</a></section>`;
}
