import {topics as originalTopics,guides,comparisons} from '../data/editorial.mjs';
import {extraTopics,extraGuides,extraComparisons,brandAnalyses,brandAnalysisSections} from '../data/expansion.mjs';
const topics=[...originalTopics,...extraTopics];
import {examples} from '../data/examples.mjs';
for(const guide of guides){if(!examples[guide.id])throw Error('Missing editorial example '+guide.id);guide.sections.push({heading:'一个具体判断例子',paragraphs:[examples[guide.id]]});}
export const articles=[...guides,...comparisons,...extraGuides,...extraComparisons,...brandAnalyses];
const articleKind=a=>a.kind==='comparison'?'套餐分析':a.kind==='brand'?'品牌档位解析':'选购指南';
export {topics};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const topicOf=a=>topics.find(t=>t.id===a.topic);
const prefix=d=>'../'.repeat(d)||'./';
const fullTitle=a=>'机场推荐｜'+a.title;
const heading=(tag,title,intro)=>`<section class="page-heading"><p class="eyebrow">${tag}</p><h1>${E(title)}</h1><p>${E(intro)}</p></section>`;
const crumb=(d,items)=>`<div class="breadcrumb"><a href="${prefix(d)}">首页</a>${items.map(([label,p])=>`<span>/</span>${p?`<a href="${prefix(d)}${p}">${E(label)}</a>`:E(label)}`).join('')}</div>`;
const cards=(list,d)=>`<div class="article-grid">${list.map(a=>`<article class="article-card" data-article="${E(a.title+' '+a.excerpt)}" data-topic="${a.topic}"><div class="article-meta"><a href="${prefix(d)}topics/${a.topic}/">${E(topicOf(a).name)}</a><span>${articleKind(a)}</span></div><h2><a href="${prefix(d)}blog/${a.id}/">${E(a.title)}</a></h2><p>${E(a.excerpt)}</p><a class="text-link" href="${prefix(d)}blog/${a.id}/">阅读全文 <span aria-hidden="true">↗</span></a></article>`).join('')}</div>`;
const topicCards=(d,limit=topics.length)=>`<div class="topic-grid">${topics.slice(0,limit).map((t,i)=>`<a class="topic-card" href="${prefix(d)}topics/${t.id}/"><span class="topic-number">${String(i+1).padStart(2,'0')} / ${articles.filter(a=>a.topic===t.id).length} 篇</span><h3>${E(t.name)}</h3><p>${E(t.intro)}</p><span class="text-link">进入专题 ↗</span></a>`).join('')}</div>`;
export function editorialHome(){return `<section class="shell editorial-home"><div class="section-heading"><div><p class="eyebrow">READ BY NEED</p><h2>机场推荐，按你的需求读。</h2></div><a class="text-link" href="./topics/">全部 ${topics.length} 个专题 ↗</a></div>${topicCards(0,8)}<div class="section-heading"><div><p class="eyebrow">THE JOURNAL</p><h2>先读懂套餐，再做选择。</h2></div><a class="text-link" href="./blog/">${articles.length} 篇文章 ↗</a></div>${cards([guides[0],comparisons[0],guides.find(a=>a.id==='coupon-validation')],0)}</section>`;}
export function brandReading(id,d=2){const list=articles.filter(a=>a.brandIds.includes(id)).sort((x,y)=>(y.kind==='brand')-(x.kind==='brand')).slice(0,3);const chosen=list.length?list:guides.filter(a=>['checkout-checklist','source-conflicts','cost-per-gb'].includes(a.id));return `<section class="shell related editorial-related"><h2>把品牌放回使用场景</h2><p class="muted">结合预算、用量与核验方法继续阅读。</p>${cards(chosen,d)}<div class="inline-links">${[...new Set(chosen.map(a=>a.topic))].map(t=>`<a href="${prefix(d)}topics/${t}/">${E(topics.find(x=>x.id===t).name)}</a>`).join('')}<a href="${prefix(d)}blog/">全部选购文章</a></div></section>`;}
function brandLinks(ids,brands,d){return `<div class="brand-reading">${ids.map(id=>{const b=brands.find(b=>b.id===id);const p=b.plans.filter(p=>p.cycle==='月付').sort((a,b)=>a.price-b.price)[0];return `<a href="${prefix(d)}brands/${b.id}/"><strong>${E(b.name)}</strong><span>参考月付 ¥${p.price} 起 · ${p.gb??'流量待核验'}${p.gb?'GB':''}</span><small>查看套餐、优惠码与来源 ↗</small></a>`;}).join('')}</div>`;}
function comparisonSections(a,brands){
 const bs=a.ids.map(id=>brands.find(b=>b.id===id));
 const enough=b=>b.plans.filter(p=>p.cycle==='月付'&&p.gb!==null&&p.gb>=a.flow).sort((x,y)=>x.price-y.price)[0];
 const ps=bs.map(enough);
 const rows=bs.map((b,i)=>{const p=ps[i];return `<tr><th scope="row"><a href="../../brands/${b.id}/">${E(b.name)}</a></th>${p?`<td>${E(p.name)}</td><td>¥${p.price}/月</td><td>${p.gb}GB/月</td><td>¥${(p.price/p.gb).toFixed(3)}</td><td>${p.gb-a.flow}GB</td>`:'<td colspan="5">所录月包未找到满足此用量且容量明确的档位</td>'}</tr>`;}).join('');
 const cash=ps.every(Boolean)?`按照月用量 ${a.flow}GB 这一假设，${bs[0].name}的最低匹配档为 ${ps[0].name}，月付 ${ps[0].price} 元；${bs[1].name}为 ${ps[1].name}，月付 ${ps[1].price} 元。两档每月支出相差 ${Math.abs(ps[0].price-ps[1].price).toFixed(2)} 元，标称容量相差 ${Math.abs(ps[0].gb-ps[1].gb)}GB。差额只反映套餐结构，无法证明速度、稳定性或平台可用性。`:'部分档位缺少容量或没有合适月包，不能直接给出同用量下的最低月成本。先补充购买页资料，再作比较。';
 const extra=bs.map(b=>{const annual=b.plans.filter(p=>p.cycle==='年付').sort((x,y)=>x.price-y.price)[0];const once=b.plans.filter(p=>p.cycle==='一次性');return `${b.name}${annual?`的最低年付参考档需一次支付 ${annual.price} 元，记录容量为 ${annual.gb??'待核验'}${annual.gb?'GB/月':''}；折合月成本 ${(annual.price/12).toFixed(2)} 元`:'暂未收录可比较的年付档'}。${once.length?`另有一次性包资料：${once.map(p=>`${p.name}，${p.price} 元、${p.gb??'待核验'}${p.gb?'GB 总量':''}`).join('；')}。一次性总量不按月刷新，应确认有效期。`:'本站未收录其一次性包资料，这不表示官网一定没有出售。'}`;});
 return [
 {heading:'先把两个品牌放进同一用量假设',paragraphs:[a.angle,`本次以每月 ${a.flow}GB、按月支付、未使用优惠码为比较基线。筛选规则是：从收录的月付档中，选择容量明确且不低于这一用量的最低价格套餐。这里的用量是假设，不是本站测得的个人消耗；若你实际使用量不同，结论也会改变。`]},
 {heading:'满足用量的参考月包怎么选',paragraphs:[cash],html:`<div class="table-scroll"><table><caption>${a.flow}GB/月场景 · 第三方参考资料，未计倍率与优惠</caption><thead><tr><th>品牌</th><th>匹配套餐</th><th>月付</th><th>标称流量</th><th>元/GB</th><th>标称余量</th></tr></thead><tbody>${rows}</tbody></table></div><p class="table-foot">余量 = 套餐标称流量 − 假设月用量。单 GB 价格 = 月付金额 ÷ 标称流量。节点倍率、附加费与折扣会改变实际成本。</p>`},
 {heading:'年付与一次性包，要换一个比较口径',paragraphs:extra},
 {heading:'推荐取舍与尚待确认的条件',paragraphs:[a.decision,...bs.map(b=>`${b.name}的资料提示：${b.note} 当前参考数据未获得登录后官网套餐确认，购买时需要复核档位名称、价格、扣流量倍率、重置周期与售后条件。`)]},
 {heading:'资料来源与下一步',paragraphs:['本篇由本站对收录的套餐数据进行计算与分析，未购买服务，也没有独立速度、延迟、丢包或解锁测试。比较结果不会按价格差异生成服务质量评分。先保存实际结算页的报价，再用自己的网络完成常用任务验证。'],html:`<ul class="source-list">${bs.map(b=>`<li><a href="${E(b.source)}" target="_blank" rel="noopener noreferrer">${E(b.name)} · ${E(b.sourceLabel)}</a><p>第三方来源记录日期 ${E(b.plans[0].sourceDate)}；本站查询于 2026-10-03。原始各档日期请查看<a href="../../brands/${b.id}/#plans">完整品牌套餐表</a>。</p></li>`).join('')}</ul>`}
 ];
}
export function renderEditorial(page,brands){
 page('topics/index.html','机场推荐专题｜预算、流量、影音与优惠码 - 云途集',`${topics.length}个机场推荐专题，覆盖新手、预算、流量、手机、电脑、影音、AI、下载与售后，组织选购文章及品牌参考。`,`<div class="shell">${heading('THE COLLECTIONS','机场推荐专题','从你的需求出发，把散落的套餐、品牌与选购问题连起来。')}${topicCards(1)}<section class="reading-note"><div><h2>选一个问题，<br>顺着线索读下去。</h2></div><div><p>每个专题都有阅读顺序、品牌参考与相关文章。这里的品牌是按套餐资料归类的候选，不代表已验证某种平台功能。</p><a class="text-link" href="../blog/">查看完整文章库</a></div></section></div>`,{depth:1});
 for(const t of topics){const list=articles.filter(a=>a.topic===t.id);page(`topics/${t.id}/index.html`,`${t.name}专题｜${list.length}篇选购与套餐分析 - 云途集`,t.intro,`<div class="shell">${crumb(2,[['机场推荐专题','topics/'],[t.name]])}${heading('COLLECTION / '+String(topics.indexOf(t)+1).padStart(2,'0'),t.name+'专题',t.intro)}<ol class="topic-steps">${t.steps.map((s,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><p>${E(s)}</p></li>`).join('')}</ol><div class="section-heading"><h2>从这些文章开始</h2><span class="muted">${list.length} 篇内容 · 2026-10-03</span></div>${cards(list,2)}<section class="related"><h2>相关品牌与套餐资料</h2><p class="muted">按公开套餐结构归类；使用表现及当前在售情况需复核。</p>${brandLinks(t.brandIds,brands,2)}</section><section class="related"><h2>换一个角度继续读</h2><div class="inline-links">${topics.filter(x=>x.id!==t.id).sort((x,y)=>y.brandIds.filter(id=>t.brandIds.includes(id)).length-x.brandIds.filter(id=>t.brandIds.includes(id)).length).slice(0,6).map(x=>`<a href="../${x.id}/">${E(x.name)}</a>`).join('')}<a href="../">全部 ${topics.length} 个专题</a></div></section></div>`,{depth:2});}
 page('blog/index.html',`机场推荐博客｜${articles.length}篇选购指南与品牌比较 - 云途集`,`机场推荐文章库：${articles.length}篇选购、品牌档位与套餐比较文章，按${topics.length}个专题筛选价格、流量、手机、电脑和优惠码问题。`,`<div class="shell">${heading('THE JOURNAL','机场推荐博客','把选择前的每一个问题，拆开讲清楚。')}<div class="article-tools"><label class="article-search">搜索文章<input id="article-search" type="search" placeholder="搜索价格、流量、年付、优惠码…" autocomplete="off"></label><details class="article-topic-picker" open><summary>按 ${topics.length} 个专题筛选</summary><div class="article-filters" role="group" aria-label="按专题筛选文章"><button data-topic-filter="all" class="active" aria-pressed="true">全部 ${articles.length}</button>${topics.map(t=>`<button data-topic-filter="${t.id}" aria-pressed="false">${E(t.name.replace('机场推荐',''))}</button>`).join('')}</div></details><p id="article-result-count" aria-live="polite">共 ${articles.length} 篇文章 · ${articles.filter(a=>a.kind==='guide').length} 篇指南 / ${articles.filter(a=>a.kind==='comparison').length} 篇套餐比较 / ${brandAnalyses.length} 篇品牌解析</p></div>${cards(articles,1)}<nav class="article-index-pagination" aria-label="文章列表分页" hidden><button id="article-previous" class="button secondary">上一页</button><div id="article-page-buttons"></div><button id="article-next" class="button secondary">下一页</button></nav><p id="article-empty" class="article-empty" hidden>没有找到相关文章。试试“流量”“月付”，或切换到全部专题。</p><div class="actions"><a class="button secondary" href="../topics/">按专题阅读</a><a class="button secondary" href="../compare/">查看套餐总表</a></div></div>`,{depth:1});
 for(const a of articles){const t=topicOf(a),sections=a.kind==='comparison'?comparisonSections(a,brands):a.kind==='brand'?brandAnalysisSections(a):a.sections;if(a.id==='gb-vs-gib')sections[0].html='<p class="technical-source">单位定义参考：<a href="https://physics.nist.gov/cuu/Units/binary.html" target="_blank" rel="noopener noreferrer">NIST：十进制与二进制前缀</a>。</p>';const checklist=a.checklist??['实际报价与参考表是否一致','节点倍率与流量周期是否明确','短期验证后再决定是否长期付款'];const ix=articles.indexOf(a);const readingChars=sections.map(s=>s.paragraphs.join('')).join('').length;
 const body=`<div class="shell journal-shell">${crumb(2,[['机场推荐博客','blog/'],[t.name,`topics/${t.id}/`],[a.title]])}<header class="journal-heading"><a class="article-kicker" href="../../topics/${t.id}/">${E(t.name)} / ${articleKind(a)}</a><h1>${E(fullTitle(a))}</h1><p class="lead">${E(a.excerpt)}</p><div class="article-meta"><span>云途集编辑部</span><time datetime="${a.date}">${a.date}</time><span>约 ${Math.max(3,Math.ceil(readingChars/300))} 分钟阅读</span></div></header><div class="journal-layout"><article class="article-prose"><details class="article-toc" open><summary>文章目录</summary><nav aria-label="文章目录">${sections.map((s,i)=>`<a href="#section-${i+1}">${String(i+1).padStart(2,'0')} · ${E(s.heading)}</a>`).join('')}<a href="#checklist">购买前核对清单</a></nav></details>${sections.map((s,i)=>`<section id="section-${i+1}"><h2>${E(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${E(p)}</p>`).join('')}${s.html??''}</section>`).join('')}<section id="checklist" class="article-checklist"><h2>把这份清单带到结算页</h2><ul>${checklist.map(c=>`<li>${E(c)}</li>`).join('')}</ul><p>核对套餐时可同时打开<a href="../../compare/">28 家套餐对比表</a>、<a href="../../coupons/">优惠码汇总</a>与<a href="../../about/">资料方法说明</a>。</p></section>${['speed-report','latency-units'].includes(a.id)?'<p class="technical-source">概念参考：<a href="https://developer.mozilla.org/en-US/docs/Glossary/Bandwidth" target="_blank" rel="noopener noreferrer">MDN：带宽</a>、<a href="https://developer.mozilla.org/en-US/docs/Glossary/Latency" target="_blank" rel="noopener noreferrer">MDN：延迟</a>。</p>':''}<div class="notice article-disclosure"><strong>本文资料口径</strong><p>${a.kind!=='guide'?'套餐数据来自各品牌页列出的第三方资料；本站计算不是官网报价。':'本文为选购方法与算例分析，涉及的品牌报价请查看品牌页所附的第三方来源。'}未提供独立测速与平台可用性保证。优惠码由站长提供，效果以结算为准。</p></div></article><aside class="journal-aside"><div class="sticky-aside"><p class="eyebrow">IN THIS COLLECTION</p><h2>${E(t.name)}</h2><p>${E(t.intro)}</p><a class="button secondary" href="../../topics/${t.id}/">浏览专题</a><hr><strong>相关品牌</strong>${brandLinks(a.brandIds,brands,2)}<a class="text-link" href="../../compare/">打开 28 家套餐总表 ↗</a></div></aside></div><section class="related"><h2>沿着问题继续阅读</h2>${cards(a.related.map(id=>articles.find(a=>a.id===id)).filter(Boolean),2)}</section><nav class="article-pagination" aria-label="相邻文章">${[articles[ix-1],articles[ix+1]].filter(Boolean).map((b,i)=>`<a href="../${b.id}/"><small>${b===articles[ix-1]?'上一篇':'下一篇'}</small><strong>${E(b.title)}</strong></a>`).join('')}</nav></div>`;
 page(`blog/${a.id}/index.html`,`${fullTitle(a)} - 云途集`,a.excerpt,body,{depth:2,type:'Article',extra:{headline:fullTitle(a),datePublished:a.date,dateModified:a.date,articleSection:t.name,author:{'@type':'Organization',name:'云途集编辑部'},publisher:{'@type':'Organization',name:'云途集'}}});
 }
 const group=(title,list)=>`<section class="map-group"><h2>${title}</h2><ul>${list.map(([label,p])=>`<li><a href="../${p}">${E(label)}</a></li>`).join('')}</ul></section>`;
 page('sitemap/index.html','机场推荐网站地图｜全部品牌、专题与博客文章 - 云途集',`云途集网站地图：浏览28个机场品牌、${topics.length}个选购专题、${articles.length}篇博客文章以及套餐对比和优惠码页面。`,`<div class="shell">${heading('THE SITE MAP','机场推荐网站地图','从这里找到全部品牌、专题和文章。')}<p>搜索引擎使用的 <a href="../sitemap.xml">XML sitemap</a> 会在构建时自动更新。</p>${group('常用入口',[['机场推荐首页',''],['套餐对比','compare/'],['优惠码','coupons/'],['选购指南','guide/'],['资料与方法','about/'],['博客文章','blog/'],['专题目录','topics/']])}${group(`${topics.length} 个专题`,topics.map(t=>[t.name,`topics/${t.id}/`]))}${group('28 个品牌',brands.map(b=>[b.name,`brands/${b.id}/`]))}${group(`${articles.length} 篇博客文章`,articles.map(a=>[a.title,`blog/${a.id}/`]))}</div>`,{depth:1});
}
