import fs from 'node:fs';
const official=JSON.parse(fs.readFileSync(new URL('../data/official-checks.json',import.meta.url),'utf8'));
const coupons=JSON.parse(fs.readFileSync(new URL('../data/coupon-reviews.json',import.meta.url),'utf8'));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lookup=b=>official.records.find(x=>x.id===b.id);
export function officialBrandEvidence(b){const r=lookup(b);return `<div class="official-evidence"><h3>官网公开资料复查 · ${official.checkedDate}</h3><p>${r.publicName?`面板公开名称为“${E(r.publicName)}”。`:''}本次公开面板能打开，公共配置可读取；套餐列表需要登录，当前官网售价、年包重置和优惠实付尚未取得。</p><p>公共配置未提供服务条款地址，这不表示品牌没有条款。${r.termsPage?'本次在浏览器打开微风注册页的服务条款链接，最终显示登录页，未读到条款正文。':''}不把前端通用提示当作已确认的品牌退款规则。</p>${r.linkedStatus!==200?`<details><summary>另一配置地址的访问记录</summary><p>面板配置列出的另一站点地址，本次${r.linkedStatus?`返回HTTP ${r.linkedStatus}`:'未能从本机访问'}。这是该地址在本次检查的结果，不能据此判断品牌停服，也不影响站长提供的推广入口被保留。</p><p>该地址：${E(r.linkedUrl)}</p></details>`:''}<p><a href="${E(r.panelUrl)}" target="_blank" rel="noopener noreferrer">查看本次检查的公开面板 ↗</a> · <a href="../../updates/#official-review">查看28家复查记录</a></p></div>`;}
export function couponCardHint(b){const r=coupons.records.find(x=>x.id===b.id);return `<p class="coupon-condition-hint">${E(r.summary)}<br><a href="../brands/${b.id}/#coupon-review-${b.id}">查看条件与历史来源 →</a></p>`;}
export function couponReview(b){if(!b.coupon)return '';const r=coupons.records.find(x=>x.id===b.id);if(!r||r.code!==b.coupon)throw Error('Coupon mismatch '+b.id);return `<aside class="coupon-review-note" id="coupon-review-${b.id}"><h3>${E(b.name)}：使用条件复查</h3><p><strong>${E(r.summary)} · 当前实付待验证</strong></p>${r.sources.length?`<p>以下为第三方历史转述，查询于${coupons.checkedDate}；未取得当前官方结算证据。部分资料含推广关系，不将这些折扣用于本站套餐价格计算。</p><ul>${r.sources.map(([name,url,date,claim])=>`<li><a href="${E(url)}" target="_blank" rel="noopener noreferrer">${E(name)} ↗</a> · ${date?`来源记录日期${E(date)}`:'原始核对日期未明确'}<br>${E(claim)}</li>`).join('')}</ul>`:''}<p><strong>本站判断：</strong>${E(r.decision)}</p><p>确认方法：保持同一套餐、周期和用户资格，比较填码前后实付，核对续费、重置费用和活动排除条件。</p></aside>`;}
export function officialReviewOverview(brands){return `<section class="library-section official-review-overview" id="official-review"><h2>官网公开面板复查</h2><p>检查${official.checkedDate}：28个由品牌入口发现的公开面板及公共配置可访问，套餐列表均要求登录。下面列出当前能确认的公开访问结果，官网套餐和优惠实付仍待确认。</p><div class="table-scroll"><table><caption>28家公开面板记录 · 不代表套餐在售、服务质量或优惠有效</caption><thead><tr><th>品牌</th><th>公开面板</th><th>官网套餐及年额度</th><th>服务条款</th><th>优惠实付</th><th>可追溯来源</th></tr></thead><tbody>${brands.map(b=>{const r=lookup(b);return `<tr><th><a href="../brands/${b.id}/#sources">${E(b.name)}</a></th><td>可打开<small>${E(r.publicName||'公开配置未提供名称字段')}</small></td><td>需登录，未确认${b.planAttribution==='disputed'?'<small>另有套餐归属疑点</small>':''}</td><td>公共配置未提供条款地址</td><td>${b.coupon?'未结算验证':'站长未提供优惠码'}</td><td><a href="${E(r.panelUrl)}" target="_blank" rel="noopener noreferrer">公开面板 ↗</a></td></tr>`;}).join('')}</tbody></table></div><p class="table-foot">公开配置中的条款地址为空不等于没有条款；其他站点地址访问失败不等于品牌停服。微风条款链接的浏览器检查显示登录页，未读取条款正文。第三方历史优惠条件见<a href="../coupons/">优惠码复查说明</a>。</p></section>`;}
