import fs from 'node:fs';
import {researchArticleSection} from './research.mjs';
import {selectPlans} from '../assets/selector.js';
const review=JSON.parse(fs.readFileSync(new URL('../data/priority-review.json',import.meta.url),'utf8'));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const priorityRecord=id=>review.records.find(r=>r.brandId===id);
export function sensitivityRows(b){const r=priorityRecord(b.id);if(!r?.focus||b.planAttribution==='disputed')return [];
 return [{label:'按实际用量',multiplier:1,reserve:0},{label:'增加10%预留',multiplier:1,reserve:10},{label:'假设2倍扣量',multiplier:2,reserve:0}].map(q=>{const result=selectPlans([b],{budget:100000,traffic:r.focus,cycle:'月付',multiplier:q.multiplier,reserve:q.reserve});const p=result.rows[0]?.plan;return {...q,usage:r.focus,required:result.required,plan:p?.name??null,price:p?.price??null,gb:p?.gb??null};});
}
export function renderPriorityReview(b,depth=2){const r=priorityRecord(b.id);if(!r)return '';const prefix='../'.repeat(depth);
 return `<section class="prose-block priority-review" id="priority-review"><p class="eyebrow">SOURCE REVIEW / 把证据说清楚</p><h2>${E(b.name)}公开证据复查</h2><p>本站复查${E(r.checkedDate)}；原套餐资料日期${E(b.plans[0].sourceDate)}。两个日期分别表示本次读取与原始记录，不能把今天的访问当作今天的官网价格核验。</p><div class="evidence-summary"><div><small>入口公共配置</small><strong>${E(r.primaryName||'未提供名称字段')}</strong><span>仅证明公开显示的名称${r.primaryName?'':'；描述为“'+E(r.primaryDescription)+'”'}</span></div><div><small>原参考表比对</small><strong>${r.referenceMatches.length}/${r.referenceMatches.length}档数值相符</strong><span>名称、金额、周期与原始GB值</span></div><div><small>当前订单与使用</small><strong>尚未核实</strong><span>现价、优惠、退款及本站测速</span></div></div><p>套餐接口仍需登录；本次没有注册或购买。多份页面可能转录同一套资料，不能把来源数量当成独立证据数量。</p><div class="table-scroll"><table><caption>${E(b.name)} · 公开资料支持的判断及缺项</caption><thead><tr><th scope="col">项目</th><th scope="col">证据状态</th><th scope="col">本次结论</th><th scope="col">来源</th></tr></thead><tbody>${r.facts.map(([topic,status,summary,url])=>`<tr><th scope="row">${E(topic)}</th><td>${E(status)}</td><td>${E(summary)}</td><td><a href="${E(url)}" target="_blank" rel="noopener noreferrer">原页面 ↗</a></td></tr>`).join('')}</tbody></table></div><details><summary>查看本次逐项比对记录 · ${r.referenceMatches.length}档</summary><p>只比对第三方表中的原始数值，不确认当前在售、年包重置或品牌归属。<a href="${E(r.referenceURL)}" target="_blank" rel="noopener noreferrer">原参考来源 ↗</a>；来源标题：${E(r.referenceHeading)}。</p><div class="table-scroll"><table><caption>原表对照 · 未计优惠</caption><thead><tr><th>引用套餐</th><th>金额</th><th>周期</th><th>原始GB值</th></tr></thead><tbody>${r.referenceMatches.map(p=>`<tr><th>${E(p.name)}</th><td>¥${p.price}</td><td>${E(p.cycle)}</td><td>${p.rawGb}</td></tr>`).join('')}</tbody></table></div></details><div class="inline-links"><a href="${E(r.panelURL)}" target="_blank" rel="noopener noreferrer">入口公开面板 ↗</a><a href="${prefix}updates/#priority-reviews">7家复查汇总</a><a href="${prefix}contact/#feedback-help">提交有来源的更正</a></div></section>`;
}
export function priorityArticleSections(b){const r=priorityRecord(b.id);if(!r)return [];
 const rows=sensitivityRows(b);return [...(rows.length?[{heading:r.question,paragraphs:[...r.analysis,'计算假设：所需标称容量=实际用量×节点扣量倍率×（1+预留比例）。节点2倍和10%预留均为演示条件，不是本品牌已核实的规则；没有把优惠计入参考月费。'],html:`<div class="table-scroll"><table><caption>${E(b.name)} · ${r.focus}GB用量的敏感性分析，本站算例</caption><thead><tr><th>假设条件</th><th>所需容量</th><th>最低满足引用档</th><th>参考月付</th><th>标称容量</th></tr></thead><tbody>${rows.map(x=>`<tr><th>${E(x.label)}</th><td>${x.required}GB</td><td>${E(x.plan||'没有足够档位')}</td><td>${x.price===null?'—':'¥'+x.price}</td><td>${x.gb===null?'—':x.gb+'GB'}</td></tr>`).join('')}</tbody></table></div><p><a href="../../select/">用自己的预算、倍率与用量重新筛选 →</a></p>`}]:[]),{heading:'本次公开证据与仍未解决的问题',paragraphs:r.facts.map(([topic,status,summary])=>topic+'（'+status+'）：'+summary),html:`<p>读取于${r.checkedDate}，本次与原参考表比对${r.referenceMatches.length}档。金额相符不等于官网确认；尚无本站购买或测速记录。</p><div class="inline-links">${[...new Set(r.facts.map(x=>x[3]))].map(url=>`<a href="${E(url)}" target="_blank" rel="noopener noreferrer">核对原来源 ↗</a>`).join('')}<a href="../../brands/${b.id}/#priority-review">查看证据对照及缺项 →</a></div>`}];
}
export function disputedArticleSections(b){const r=priorityRecord(b.id);if(!r||b.planAttribution!=='disputed')return null;
 return [{heading:'先确认套餐属于谁，再讨论价格',paragraphs:[r.facts[0][2],'本次没有取得该入口的当前套餐列表。名称相似可能是简称、资料编辑错误或其他原因，现有证据不能确定。本站保留入口和原优惠码，也不据此判断品牌停服。']},{heading:'能确认的公开记录与不能确认的订单',paragraphs:[`公共配置名称：${r.primaryName}。原参考来源标题：${r.referenceHeading}。两者均在${r.checkedDate}读取；原资料的各档日期为${b.plans[0].sourceDate}。`,'这些记录能说明页面公开显示什么，不能证明当前有相同套餐、相同额度或相同优惠。原表数值一致也不会消除归属疑点。']},{heading:'保留原始引用，暂停报价比较',paragraphs:['首页、起价排序和勾选金额对比不再把这些数值作为该品牌报价。选购工具继续排除这些未确认档位。下面保留引用供读者追溯，不生成最低满足档、升级单价或推荐周期。'],html:`<details class="unverified-plans"><summary>展开归属待核实的原参考表</summary><div class="table-scroll"><table><caption>归属待核实 · 原参考来源的历史引用</caption><thead><tr><th>原表名称</th><th>原金额</th><th>周期</th><th>原GB值</th></tr></thead><tbody>${r.referenceMatches.map(p=>`<tr><th>${E(p.name)}</th><td>¥${p.price}</td><td>${E(p.cycle)}</td><td>${p.rawGb}</td></tr>`).join('')}</tbody></table></div></details>`},{heading:'什么证据可以解决归属疑点',paragraphs:['需要能够同时对应入口域名、品牌名、套餐名称、付款周期、流量规则及日期的当前套餐页面。若是改名，还需要可追溯的官方改名说明；仅有另一个推广站的相同表格不够。','反馈时请隐藏账号、订单和支付信息。本站收到资料后先核对来源，再更新金额比较与留存记录；没有交易证据时仍不会把优惠标成生效。'],html:`<p><a href="../../brands/${b.id}/#feedback">提交${E(b.name)}资料更正 →</a></p>`},...priorityArticleSections(b),researchArticleSection(b)];
}
export function priorityOverview(brands){return `<section class="library-section" id="priority-reviews"><h2>7家重点公开证据复查</h2><p>5家补充选购边界分析；Firefly、极连云保留归属疑点。比对42个原参考档位，未取得当前官网订单与本站测速。本次复查未新增品牌、优惠码或实测评分。</p><div class="history-directory">${review.records.map(r=>`<a href="../brands/${r.brandId}/#priority-review">${E(brands.find(b=>b.id===r.brandId).name)} · 证据与缺项 →</a>`).join('')}</div></section>`;}
