import {officialReviewOverview} from './official-review.mjs';
import {speedOverview} from './speed-research.mjs';
import {quotaLabel} from '../assets/quota.js';
import fs from 'node:fs';
const sourceChecks=JSON.parse(fs.readFileSync(new URL('../data/source-checks.json',import.meta.url),'utf8'));
const accessCheck=id=>sourceChecks.records.find(r=>r.id===id);
const accessLabel=id=>{const entry=accessCheck(id)?.entry;return entry?.status===200?(entry.kind==='route-check'?'可访问 · 线路检测页':'可访问 · 公开页面'):'未确认可访问';};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intro=(tag,title,copy)=>`<section class="page-heading"><p class="eyebrow">${tag}</p><h1>${title}</h1><p>${copy}</p></section>`;
export const readerActions=b=>`<div class="reader-actions"><button type="button" class="reader-action" data-save-brand="${b.id}" disabled aria-pressed="false" aria-label="收藏 ${E(b.name)}">☆ 收藏</button><button type="button" class="reader-action" data-compare-brand="${b.id}" disabled aria-pressed="false" aria-label="对比 ${E(b.name)}">＋ 加入对比</button></div>`;
export const comparisonPicker=brands=>`<section id="pick-compare" class="comparison-picker"><p class="eyebrow">COMPARE YOUR SHORTLIST</p><h2>选 2～4 家，放在一起比较</h2><p>每家采用最低月付档和最低年付档；容量不同，不能将起价直接当作同用量结论。</p><details class="compare-choice-picker" open><summary>更改所选品牌 · 28 家</summary><fieldset id="comparison-choices"><legend>选择品牌 · 最多 4 家</legend><div class="comparison-choices">${brands.map(b=>`<label><input type="checkbox" value="${b.id}"><span>${E(b.name)}</span></label>`).join('')}</div></fieldset><div class="actions"><button type="button" class="button secondary" data-close-choice>查看选中品牌的对比</button><button type="button" class="reader-action" data-clear-comparison>清空选择</button></div></details><p id="picked-compare-status" role="status" aria-live="polite">请勾选 2～4 家品牌。</p><p class="reader-loading" data-reader-loading>正在载入互动功能；下方完整套餐表可直接阅读。</p><div id="picked-brand-comparison" class="picked-brand-comparison"></div><noscript><p>勾选对比需要启用 JavaScript；下方完整套餐表仍可直接比较。</p></noscript><a class="text-link" href="../select/">有明确预算和流量？使用套餐选购工具 →</a></section>`;
export function renderReader(page,brands,articles,topics,out){
 const documents=[...brands.map(b=>({id:b.id,type:'brand',title:b.name+' '+b.english,path:'brands/'+b.id+'/',description:b.summary,text:[b.audience,b.tag,b.line,b.coupon,...b.plans.map(p=>`${p.name} ${p.cycle} ${p.price}元 ${quotaLabel(p)}`)].join(' ')})),...articles.map(a=>({id:a.id,type:'article',title:a.title,path:'blog/'+a.id+'/',description:a.excerpt,text:[topics.find(t=>t.id===a.topic).name,...a.brandIds.map(id=>brands.find(b=>b.id===id).name),...(a.sections||[]).map(s=>s.heading+' '+(s.paragraphs||[]).join(' ')),a.flow?`${a.flow}GB`:''].join(' ')})),...topics.map(t=>({id:t.id,type:'topic',title:t.name,path:'topics/'+t.id+'/',description:t.intro,text:(t.steps||[]).join(' ')}))];
 fs.writeFileSync(out+'/assets/catalog.json',JSON.stringify({brands,documents}));
 page('search/index.html','全站搜索｜品牌、文章与专题 - 云途集','搜索机场品牌、套餐流量、选购文章与专题，快速找到相关资料。',`<div class="shell reader-shell">${intro('FIND A GOOD READ','找到你想看的内容','品牌、文章、专题，在这里一起搜索。')}<form id="site-search-form" class="site-search-form" role="search"><label>搜索内容<input type="search" name="q" placeholder="如：微风、200GB、年付" autocomplete="off"></label><label>内容类型<select><option value="all">全部内容</option><option value="brand">品牌资料</option><option value="article">博客文章</option><option value="topic">推荐专题</option></select></label><button class="button primary" type="submit">搜索</button></form><p id="site-search-status" role="status" aria-live="polite"></p><p data-reader-loading>正在载入搜索目录。</p><div id="site-search-results" class="reader-grid"></div><button id="site-search-more" class="button secondary" hidden>显示更多</button><noscript><p>互动搜索需要启用 JavaScript，也可直接浏览以下目录。</p><a class="button secondary" href="../sitemap/">打开全部文章与品牌目录</a></noscript><div class="inline-links"><a href="../topics/">按专题阅读</a><a href="../#brands">浏览 28 个品牌</a><a href="../blog/">全部博客文章</a></div></div>`,{depth:1,indexable:false});
 page('library/index.html','我的收藏与最近浏览 - 云途集','在自己的浏览器里保存品牌收藏和最近浏览记录，无需注册。',`<div class="shell reader-shell">${intro('YOUR READING SHELF','我的阅读清单','无需注册。收藏和最近浏览保存在当前浏览器，不上传到本站。')}<p class="reader-note">不同设备之间不会自动同步；清除浏览器数据后，记录会消失。最近浏览最多记录 12 条品牌、文章与专题。</p><p data-storage-notice hidden></p><p data-reader-loading>正在读取当前浏览器的阅读记录。</p><section class="library-section"><div class="section-title"><h2>收藏的品牌</h2><button class="reader-action" data-clear-favorites>清空收藏</button></div><div id="saved-brands" class="reader-grid"></div></section><section class="library-section"><div class="section-title"><h2>最近浏览</h2><button class="reader-action" data-clear-recent>清空最近浏览</button></div><div id="recent-reading" class="reader-grid"></div></section><noscript><p>保存与展示阅读记录需要启用 JavaScript。</p></noscript><a class="button secondary" href="../#brands">继续浏览品牌</a></div>`,{depth:1,indexable:false});
 page('updates/index.html','套餐资料核验与网站更新记录 - 云途集','查看 28 个品牌的资料来源日期、官网与优惠码核验状态，以及网站功能更新记录。',`<div class="shell reader-shell">${intro('EVIDENCE & UPDATES','每一次更新，都说明依据','把来源日期、当前核验状态和网站功能更新分开记录。')}<div class="notice"><strong>当前资料边界</strong><p>目前套餐引用第三方公开资料；官网套餐、结算优惠与使用表现尚未独立验证。“待验证”不等于有效或失效，也不代表服务状态。</p></div><section class="library-section"><h2>28 家资料状态</h2><div class="table-scroll"><table><caption>资料整理于 2026-10-03；来源日期为原资料记录日期，入口访问仅表示 HTTP 检查结果</caption><thead><tr><th>品牌</th><th>来源记录日期</th><th>入口访问</th><th>第三方套餐表复查</th><th>官网套餐</th><th>优惠码结算</th><th>资料依据</th></tr></thead><tbody>${brands.map(b=>`<tr><th><a href="../brands/${b.id}/#sources">${E(b.name)}</a></th><td>${E(b.plans[0].sourceDate)}</td><td>${E(accessLabel(b.id))}<small>检查 ${E(sourceChecks.checkedDate)}</small></td><td>${accessCheck(b.id).referenceReview.matched} / ${accessCheck(b.id).referenceReview.total} 档匹配<small>原始金额、周期、容量数值；不确认重置周期</small></td><td>尚未独立确认</td><td>${b.coupon?'待验证':'未提供优惠码'}</td><td><a href="${E(b.source)}" target="_blank" rel="noopener noreferrer">查看第三方来源 ↗</a></td></tr>`).join('')}</tbody></table></div></section>${speedOverview(brands)}${officialReviewOverview(brands)}<section class="library-section"><h2>网站更新记录</h2><ol class="update-timeline"><li><time datetime="2026-10-03">2026-10-03</time><h3>28家测速资料与首页品牌入口</h3><p>逐家整理外部历史测速，保留采样日期、测试环境、来源与局限。22家有外部报告数值，其余分别说明图证缺项、图证疑点或未找到合适记录；未进行本站测速，也不生成跨品牌速度排名。首页28个品牌新增前往官方按钮，保留推广链接说明与原优惠码复制功能。</p></li><li><time datetime="2026-10-03">2026-10-03</time><h3>公开面板与优惠条件复查</h3><p>检查28个由品牌入口发现的面板，公开配置均可读取，套餐均需登录。补充11个优惠码的核验说明，其中9个保留第三方历史条件及来源。微风折扣说法不同，无忧和微风有活动日期已过的历史记录；当前实付仍未验证。Firefly与极连云引用套餐名称归属存在疑点，停止加入自动选购候选。</p></li><li><time datetime="2026-10-03">2026-10-03</time><h3>外部历史证据与流量口径更正</h3><p>补充7个品牌的8份外部历史报告，逐条列测试日期、环境、样本和局限；28家加入按实际用量的成本分析。查看灵动云套餐原图后，将穿云改为70GB/年口径；其他缺少重置依据的年付小包不再按每月流量筛选和计算单价。所有历史报告均有商业关联，未取得原始日志，本站尚未复测。</p></li><li><time datetime="2026-10-03">2026-10-03</time><h3>搜索描述与资料透明度更新</h3><p>逐页补充文章、专题和品牌搜索描述，修正重复标题，补充预算、付款周期与资料分歧的对照表。复查 28 个公开入口和 28 个第三方来源地址，检查时均可访问；逐项比对 182 个参考档位的金额、付款周期和 GB 字段，与所引用的第三方表格一致。公开入口均为线路检测页，未获得登录后的套餐及优惠结算数据。</p></li><li><time datetime="2026-10-03">2026-10-03</time><h3>读者工具上线</h3><p>加入品牌勾选对比、收藏、最近浏览、全站搜索与资料状态汇总。功能更新不代表重新核验全部套餐价格。</p></li><li><time datetime="2026-10-03">2026-10-03</time><h3>品牌连续浏览与优惠码复制</h3><p>品牌详情支持上一家、下一家和完整目录，首页优惠码支持点击复制。</p></li><li><time datetime="2026-10-03">2026-10-03</time><h3>套餐资料与选购内容整理</h3><p>整理 28 家品牌、11 个站长提供的优惠码、120 篇文章和 24 个专题，保留来源与核验边界。</p></li></ol></section><section class="prose-block"><h2>如何补充或更正资料</h2><p>请提供品牌名、套餐名、官方页面地址、截图日期、付款周期与流量口径。如反馈优惠码，请同时说明适用套餐、实付变化和验证日期，隐藏订单号、账号和支付信息。</p><p>经核对后，再更新对应品牌状态与变更记录；不把提交的反馈自动标为已验证。</p><a class="button secondary" href="../contact/">联系本站，提交资料</a></section></div>`,{depth:1});
}
