import fs from 'node:fs';
import {renderSpeedRecord} from './speed-research.mjs';
const research=JSON.parse(fs.readFileSync(new URL('../data/research.json',import.meta.url),'utf8'));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const monthly=b=>b.plans.filter(p=>p.cycle==='月付'&&Number.isFinite(p.gb)).sort((a,c)=>a.price-c.price);
const fit=(b,need)=>monthly(b).find(p=>p.gb>=need);
function evidenceHtml(b){const rows=research.records.filter(r=>r.brandId===b.id);return `<p class="muted">查询于 ${research.checkedDate}。以下为其他发布者的历史报告，均含推广关系；本站未复测，也未取得原始日志。引用不等于确认测量真实性。</p>${rows.length?rows.map(r=>`<article class="evidence-note"><p class="eyebrow">外部历史资料 / ${E(r.publisher)}</p><h3>${E(r.testDate)} · ${r.sample} 个节点</h3><p class="evidence-environment">${E(r.environment)}</p><p><strong>发布者记录：</strong>${E(r.finding)}</p><p><strong>证据局限：</strong>${E(r.limit)}</p><p><strong>本站分析：</strong>${E(r.analysis)}</p><div class="inline-links"><a href="${E(r.url)}" target="_blank" rel="noopener noreferrer">查看发布者原文 ↗</a>${r.artifact?`<a href="${E(r.artifact)}" target="_blank" rel="noopener noreferrer">查看公开套餐原图 ↗</a>`:''}</div></article>`).join(''):'<p>此前的专题记录未收录该品牌完整报告。本轮新增的外部测速资料及缺项说明见上方测速栏目；它们不能证明当前速度、晚高峰稳定性或平台解锁已经本站验证。</p>'}`;}
export function renderResearch(b,brands){
 if(b.planAttribution==='disputed')return `<section class="prose-block" id="cost-analysis"><h2>${E(b.name)}：先核对套餐归属</h2><p>引用套餐与当前入口的对应关系尚未确认，暂停生成最低满足档、单位价格和升级建议。原数据在套餐与资料变更栏目折叠保留。</p><a class="text-link" href="#priority-review">查看本次证据与缺项 →</a></section>${renderSpeedRecord(b)}<section class="prose-block" id="evidence"><h2>外部历史证据与本站判断</h2>${evidenceHtml(b)}</section>`;
 const needs=[30,100,200,500,1000],plans=monthly(b);
 const rows=needs.map(n=>{const p=fit(b,n);return `<tr><th scope="row">${n}GB/月</th>${p?`<td>${E(p.name)}<small>${p.gb}GB/月</small></td><td>¥${p.price}/月</td><td>${p.gb-n}GB</td><td>¥${(p.price/n).toFixed(3)}</td>`:'<td colspan="4">没有容量明确且足够的收录月包</td>'}</tr>`;}).join('');
 const best=plans.toSorted((a,c)=>a.price/a.gb-c.price/c.gb)[0];
 const rises=plans.slice(1).flatMap((p,i)=>{const prev=plans[i];return p.price/p.gb>prev.price/prev.gb?[`从${prev.name}升级至${p.name}，标称单价由${(prev.price/prev.gb).toFixed(3)}升至${(p.price/p.gb).toFixed(3)}元/GB。容量越大不一定单价越低；只有新增容量或已确认权益满足需求时才有升级理由。`]:[];});
 const candidates=brands.filter(c=>c.planAttribution!=='disputed').flatMap(c=>{const p=fit(c,200);return p?[{b:c,p}]:[];}).sort((a,c)=>a.p.price-c.p.price||a.b.id.localeCompare(c.b.id)).slice(0,3);
 return `<section class="prose-block" id="cost-analysis"><p class="eyebrow">ANALYSIS / 用量决定档位</p><h2>${E(b.name)}：五种用量，怎样花钱</h2>${b.planAttribution==='disputed'?'<p class="notice">这些第三方套餐的品牌归属尚未确认；下表仅作引用数据的条件算例，不参与自动选购候选。</p>':''}<p>本站按所收录参考月包计算：每月需求固定为下表数值，选择容量足够且月付最低的档。未计优惠、节点倍率、附加费或容量结转；用量是假设，不是实测。金额和容量的来源是<a href="${E(b.source)}" target="_blank" rel="noopener noreferrer">${E(b.sourceLabel)}</a>，原记录日期 ${E(b.plans[0].sourceDate)}，当前在售情况需复核。</p><div class="table-scroll"><table class="research-cost-table"><caption>${E(b.name)} · 按实际假设用量计算支出，人民币</caption><thead><tr><th>假设需求</th><th>最低满足月包</th><th>月支出</th><th>标称余量</th><th>元/实际GB</th></tr></thead><tbody>${rows}</tbody></table></div><p class="table-foot">元/实际GB = 月付金额 ÷ 假设实际用量；余量 = 标称月容量 − 假设用量。与月费 ÷ 套餐总容量的“标称单价”不同，未使用的额度不会减少订单金额。</p>${best?`<p><strong>容量单价与实际支出：</strong>本品牌所录月包中，${E(best.name)}的标称成本最低，约¥${(best.price/best.gb).toFixed(3)}/GB，但每月仍须支付¥${best.price}。月需30GB时，${fit(b,30)?`最低满足档的支出为¥${fit(b,30).price}，按30GB实际用量约¥${(fit(b,30).price/30).toFixed(3)}/GB`:'暂不能据资料找到满足档'}。两项指标回答不同问题。</p>`:'<p>月容量资料不足，不能生成可靠的单价结论。</p>'}${rises.map(s=>'<p><strong>升级取舍：</strong>'+E(s)+'</p>').join('')}<h3>放进同样的200GB月需求，继续比较</h3><p>按全部收录月包、容量明确且不少于200GB的同一规则，支付金额最低的前三个候选如下。这是预算候选，未控制节点质量与其他权益，不是服务表现排名。</p><ul>${candidates.map(({b:c,p})=>`<li><a href="../${c.id}/#cost-analysis">${E(c.name)}</a>：${E(p.name)}，¥${p.price}/月、${p.gb}GB，标称余量${p.gb-200}GB。<small>资料提示：${E(c.note)}</small></li>`).join('')}</ul><p><a href="../../select/">输入自己的用量重新筛选 →</a> · <a href="../../blog/${b.id}-plan-analysis/">阅读本品牌完整档位解析 →</a></p></section>${renderSpeedRecord(b)}<section class="prose-block" id="evidence"><p class="eyebrow">EVIDENCE / 先看记录条件</p><h2>外部历史证据与本站判断</h2>${evidenceHtml(b)}</section>`;
}
export function researchArticleSection(b){return {heading:'外部历史资料，能支持什么判断',paragraphs:[],html:renderSpeedRecord(b)+evidenceHtml(b)+`<p><a href="../../brands/${b.id}/#cost-analysis">查看五种用量的成本分析</a> · <a href="../../brands/${b.id}/#evidence">查看品牌历史证据记录</a></p>`};}
